baseURL: https://www.codefordurham.com/
languageCode: en-us
title: Code with Durham
theme: PaperMod
languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Code of Conduct
          url: code-of-conduct
        - name: Projects
          url: project
outputs:
  home: ["HTML", "RSS", "JSON"]
params:
  env: production
  enableSearch: true
  enableCodeCopy: true
  project:
    showAuthor: true
  profileMode:
    enabled: true
    subtitle: "Volunteer civic hackers working together with local government and nonprofits to help solve local issues in and around Durham, North Carolina."
    imageUrl: logo.svg
    imageTitle: Code with Durham logo
    imageWidth: 256
    imageHeight: 256
  showBreadCrumbs: true
  showCodeCopyButtons: true
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: true
  showWordCount: true
  socialIcons:
    - name: github
      url: https://github.com/codefordurham
    - name: discord
      url: https://discord.gg/JvCyFZ2YMK
    - name: twitter
      url: https://twitter.com/codefordurham
    - name: facebook
      url: https://www.facebook.com/codefordurham/
